const data = [
  {
    id: 1,
    title: "Buy coffee",
    priority: "",
    description: "I really need to buy some",
    done: false,
  },
  {
    id: 2,
    title: "Read a book",
    priority: "",
    description: "Read and get better",
    done: false,
  },
  {
    id: 3,
    title: "Language practice",
    priority: "",
    description: "Voy a hablar español!",
    done: false,
  },
  {
    id: 4,
    title: "Go to the gym",
    priority: "",
    description: "Work out is a must",
    done: false,
  },
  {
    id: 5,
    title: "Go see Kattie",
    priority: "",
    description: "Ain't she gorgeous?",
    done: false,
  },
  // {
  //   id: 6,
  //   title: "Blabla",
  //   priority: "",
  //   description: "Filler text",
  //   done: false,
  // },
  // {
  //   id: 7,
  //   title: "Blablabla",
  //   priority: "",
  //   description: "Filler text",
  //   done: false,
  // },
  // {
  //   id: 8,
  //   title: "Filler line",
  //   priority: "",
  //   description: "Filler text",
  //   done: false,
  // },
  // {
  //   id: 9,
  //   title: "Filler line 2",
  //   priority: "",
  //   description: "Filler text",
  //   done: false,
  // },
  // {
  //   id: 10,
  //   title: "Filler line 3",
  //   priority: "",
  //   description: "Filler text",
  //   done: false,
  // },
  // {
  //   id: 11,
  //   title: "Filler line 4",
  //   priority: "",
  //   description: "Filler text",
  //   done: false,
  // },
  // {
  //   id: 12,
  //   title: "Filler line 5",
  //   priority: "",
  //   description: "Filler text",
  //   done: false,
  // },
  // {
  //   id: 13,
  //   title: "Filler line 6",
  //   priority: "",
  //   description: "Filler text",
  //   done: false,
  // },
  // {
  //   id: 14,
  //   title: "Filler line 7",
  //   priority: "",
  //   description: "Filler text",
  //   done: false,
  // },
];

export default data;
